services:
  flowise:
    image: elestio/flowiseai
    restart: always
    environment:
      - PORT=3000
      - FLOWISE_FILE_SIZE_LIMIT=300mb 
      # - FLOWISE_USERNAME=${USERNAME}
      # - FLOWISE_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
      # - "127.0.0.1:3000:3000"
    volumes:
      - ./data/flowise/.flowise:/root/.flowise
      - ./data/html:/root/html

  api:
    # image: localai/localai:latest-aio-cpu
    # For a specific version:
    # image: localai/localai:v2.20.1-aio-cpu
    # For Nvidia GPUs decomment one of the following (cuda11 or cuda12):
    # image: localai/localai:v2.20.1-aio-gpu-nvidia-cuda-11
    # image: localai/localai:v2.20.1-aio-gpu-nvidia-cuda-12
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-11
    image: localai/localai:latest-gpu-nvidia-cuda-12
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    # environment:
      # - DEBUG=true
      # ...
    volumes:
      - ./data/localai/models:/build/models:cached
      # - ./data/localai/models:/build/models
       
  postgres:
    # Official Postgres image from DockerHub (we use the last version)
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at



  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
